version: "3"
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    networks:
      - zipkin
# kafka and zookeeper
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
#kafka magic
  kafka-magic:
    image: 'digitsy/kafka-magic:latest'
    ports:
      - '8080:8080'
    environment:
      - KAFKA_BROKER_LIST=kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_TOPIC=zipkin
      - KAFKA_CONSUMER_GROUP=zipkin
      - KAFKA_CONSUMER_OFFSET=earliest
      - KAFKA_CONSUMER_ENABLE_AUTO_COMMIT=true
      - KAFKA_CONSUMER_AUTO_COMMIT_INTERVAL_MS=1000
      - KAFKA_CONSUMER_SESSION_TIMEOUT_MS=30000
      - KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS=3000
      - KAFKA_CONSUMER_FETCH_MAX_BYTES=52428800
      - KAFKA_CONSUMER_FETCH_MAX_WAIT_MS=100
      - KAFKA_CONSUMER_FETCH_MIN_BYTES=1
      - KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES=1048576
      - KAFKA_CONSUMER_RECONNECT_BACKOFF_MS=50
      - KAFKA_CONSUMER_RETRY_BACKOFF_MS=100
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - KAFKA_CONSUMER_ENABLE_AUTO_COMMIT=true
      - KAFKA_CONSUMER_AUTO_COMMIT_INTERVAL_MS=1000
      - KAFKA_CONSUMER_SESSION_TIMEOUT_MS=30000
      - KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS=3000
      - KAFKA_CONSUMER_FETCH_MAX_BYTES=52428800
      - KAFKA_CONSUMER_FETCH_MAX_WAIT_MS=100
      - KAFKA_CONSUMER_FETCH_MIN_BYTES=1
      - KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES=1048576
      - KAFKA_CONSUMER_RECONNECT_BACKOFF_MS=50
      - KAFKA_CONSUMER_RETRY_BACKOFF_MS=100
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - KAFKA_CONSUMER_ENABLE_AUTO_COMMIT=true
      - KAFKA_CONSUMER_AUTO_COMMIT_INTERVAL_MS=1000
      - KAFKA_CONSUMER_SESSION_TIMEOUT_MS=30000
      - KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS=3000
      - KAFKA_CONSUMER_FETCH_MAX_BYTES=52428800
      - KAFKA_CONSUMER_FETCH_MAX_WAIT_MS=100
      - KAFKA_CONSUMER_FETCH_MIN_BYTES=1
      - KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES=1048576
    depends_on:
      - kafka
      - zookeeper
#elk stack
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
      container_name: elasticsearch
      environment:
      - discovery.type=single-node
      ports:
      - "9200:9200"
      - "9300:9300"
      networks:
      - elk
      - zipkin
  kibana:
      image: docker.elastic.co/kibana/kibana:7.6.2
      container_name: kibana
      ports:
      - "5601:5601"
      environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      depends_on:
      - elasticsearch
      networks:
      - elk
  logstash:
      image: docker.elastic.co/logstash/logstash:7.6.2
      container_name: logstash
      ports:
      - "5000:5000"
      - "5044:5044"
      volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      depends_on:
      - elasticsearch
      networks:
      - elk